### PR TITLE
Added Hexagon Spinners (Dark and Light)

### PR DESCRIPTION
**Pull request by ScottMichaud**
Added two spinners. They're similar to "dots" except that there are six of them. Dark and Light themes (for light and dark pages, respectively) are available. They have been added to example.html.

### CODE REVIEW

**Comment by ScottMichaud** [comment]
By the way, what is the better convention? "Dark" and "Light" referring to dark and light spinners, which work best on light and dark themes, respectively? Or would it be better for "Dark" and "Light" to refer to the themes they are designed for, and not the objects themselves?

I'd normally prefer the latter, but for some reason thought the former made more sense in this case.

**Comment by jlong** [comment]
I'd suggest that they refer to the objects themselves.

**Comment by ScottMichaud** [comment]
Cool. That's how they are now.

**Comment by jlong** [comment]
@ScottMichaud Hey Scott! I went ahead and pulled in a modified version of this with only one theme. I figure people can modify the colors if they want it to work on a dark background. It's available in the 2.0.0 release.

**Pull request closed without merging**
